-- 1. Таблица Портфолио
CREATE TABLE portfolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT NOT NULL
);

-- 2. Таблица Эскизов
CREATE TABLE sketches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  image_url TEXT NOT NULL,
  status TEXT DEFAULT 'free' CHECK (status IN ('free', 'booked')),
  price TEXT
);

-- 3. Таблица Записей (Бронирований)
CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  client_name TEXT NOT NULL,
  contact TEXT NOT NULL,
  idea TEXT,
  sketch_id BIGINT REFERENCES sketches(id),
  selected_date DATE NOT NULL,
  selected_time TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'rescheduled')),
  reference_url TEXT
);

-- Настройка RLS (Row Level Security)
-- Разрешаем всем читать портфолио и эскизы
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON portfolio FOR SELECT USING (true);

ALTER TABLE sketches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON sketches FOR SELECT USING (true);

-- Разрешаем анонимно создавать заявки, но читать их может только админ (мастер)
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous insert" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin select" ON bookings FOR SELECT USING (auth.role() = 'authenticated');
