-- 1. Таблица Категорий Портфолио
CREATE TABLE portfolio_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL UNIQUE
);

-- 2. Таблица Портфолио
CREATE TABLE portfolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT NOT NULL,
  is_featured BOOLEAN DEFAULT false
);

-- 3. Таблица Эскизов
CREATE TABLE sketches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  image_url TEXT NOT NULL,
  status TEXT DEFAULT 'free' CHECK (status IN ('free', 'booked')),
  price TEXT
);

-- 4. Таблица Записей (Бронирований)
CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  client_name TEXT NOT NULL,
  contact TEXT NOT NULL,
  idea TEXT,
  sketch_id BIGINT REFERENCES sketches(id),
  selected_date DATE NOT NULL,
  selected_time TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'rescheduled')),
  reference_url TEXT
);

-- 5. Таблица Заблокированных Дат
CREATE TABLE blocked_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  date DATE NOT NULL UNIQUE
);

-- Настройка RLS (Row Level Security)
ALTER TABLE portfolio_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON portfolio_categories FOR SELECT USING (true);
CREATE POLICY "Allow admin all" ON portfolio_categories FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON portfolio FOR SELECT USING (true);
CREATE POLICY "Allow admin all" ON portfolio FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE sketches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON sketches FOR SELECT USING (true);
CREATE POLICY "Allow admin all" ON sketches FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous insert" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin select" ON bookings FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow admin update" ON bookings FOR UPDATE USING (auth.role() = 'authenticated');

ALTER TABLE blocked_dates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON blocked_dates FOR SELECT USING (true);
CREATE POLICY "Allow admin all" ON blocked_dates FOR ALL USING (auth.role() = 'authenticated');
